In [1]:
import uarray

import numpy as np
import logging
import pprint
import graphviz

In [2]:
def add(a, b):
    return a + b

In [3]:
# uarray.enable_logging()

In [4]:
def call_add(x, y):
    return uarray.optimize(x.shape, y.shape)(add)(x, y)

In [5]:
x = np.arange(4, dtype="float64")
xx = x.reshape(4,1)
y = np.ones(5, dtype="float64")
z = np.ones((3,4), dtype="float64")

In [6]:
x + z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [7]:
call_add(x, z)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [8]:
xx + y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [9]:
call_add(xx, y)

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])