# Numpy Compat

In [23]:
from uarray import *
import numpy as np


In [24]:
args = [np.arange(1000), np.arange(10)]

In [25]:
@optimize
def some_fn(a, b):
    return np.multiply.outer(a, b)[5]

In [26]:
print(some_fn.__optimize_steps__['ast_as_source'])



def fn(a, b):
    i_39 = 5
    i_41 = a
    i_42 = b
    i_40 = np.multiply.outer(i_41, i_42)
    i_38 = i_40[i_39]
    return i_38



In [27]:
some_fn(*args)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [28]:
@optimize
def some_fn_t(a, b):
    a = a.has_dim(1)
    b = b.has_dim(1)
    return np.multiply.outer(a, b)[5]

In [29]:
print(some_fn_t.__optimize_steps__['ast_as_source'])



def fn(a, b):
    i_48 = 1
    i_44 = ([0] * i_48)
    for i_49 in range(i_48):
        i_50 = (b.shape[0],)[i_49]
        i_44[i_49] = i_50
    i_43 = np.empty(tuple(i_44))
    i_45 = b.shape[0]
    for i_46 in range(i_45):
        i_53 = 5
        i_54 = a
        i_51 = i_54[i_53]
        i_55 = i_46
        i_56 = b
        i_52 = i_56[i_55]
        i_47 = (i_51 * i_52)
        i_43[i_46] = i_47
    return i_43



In [30]:
some_fn_t(np.arange(10), np.arange(10))

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [31]:
%time some_fn(*args)

CPU times: user 240 µs, sys: 126 µs, total: 366 µs
Wall time: 315 µs


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [32]:
%time some_fn_t(*args)

CPU times: user 25 µs, sys: 0 ns, total: 25 µs
Wall time: 30 µs


array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])