# 2018.11.02 Transpose and Reverse

In [1]:
from uarray import *

## Basic testing
### scalar

In [2]:
A = unbound_with_shape("A", 0)
A

Scalar(Content(Unbound('', variable_name=A)))

In [3]:
assert replace(Transpose(vector(), A)) == A

### Vector

In [4]:
B = unbound_with_shape("B", 1)
B

Sequence(Unbound('', variable_name=B_shape_0),
         UnaryFunction(Scalar(Content(CallUnary(GetItem(Unbound('')),
                                                Unbound('')))),
                       Unbound('', variable_name=i0)))

In [5]:
i = Unbound("i")
B_indexed = replace(Index(vector_of(i), B))
B_indexed

Scalar(Content(CallUnary(GetItem(Unbound('', variable_name=B)),
                         Content(Unbound('i')))))

Should be same as B (but with temp variables different)

In [6]:
B_transposed = Transpose(vector(0), B)
replace(B_transposed)

Sequence(Unbound('', variable_name=B_shape_0),
         UnaryFunction(Scalar(Content(CallUnary(GetItem(Unbound('')),
                                                Unbound('')))),
                       Unbound('', variable_name=i1)))

In [7]:
B_indexed

Scalar(Content(CallUnary(GetItem(Unbound('', variable_name=B)),
                         Content(Unbound('i')))))

In [8]:
assert replace(Index(vector_of(i), Transpose(vector(0), B))) == B_indexed

### Matrix

In [9]:
C = unbound_with_shape("B", 2)
C

Sequence(Unbound('', variable_name=B_shape_0),
         UnaryFunction(Sequence(Unbound('', variable_name=B_shape_1),
                                UnaryFunction(Scalar(Content(CallUnary(GetItem(CallUnary(GetItem(Unbound('')),
                                                                                         Unbound(''))),
                                                                       Unbound('')))),
                                              Unbound('', variable_name=i6))),
                       Unbound('', variable_name=i5)))

In [10]:
j  = Unbound("j")
C_indexed = replace(Index(vector_of(i, j), C))
C_indexed

Scalar(Content(CallUnary(GetItem(CallUnary(GetItem(Unbound('')),
                                           Content(Unbound('i')))),
                         Content(Unbound('j')))))

#### Identity

In [11]:
C_transposed_identity = Transpose(vector(0, 1), C)
replace(C_transposed_identity)

Sequence(Unbound('', variable_name=B_shape_0),
         UnaryFunction(Sequence(Unbound('', variable_name=B_shape_1),
                                UnaryFunction(Scalar(Content(CallUnary(GetItem(CallUnary(GetItem(Unbound('')),
                                                                                         Unbound(''))),
                                                                       Unbound('')))),
                                              Unbound('', variable_name=i9))),
                       Unbound('', variable_name=i7)))

In [12]:
replace(Index(vector_of(i, j), C_transposed_identity))

Scalar(Content(CallUnary(GetItem(CallUnary(GetItem(Unbound('')),
                                           Content(Unbound('i')))),
                         Content(Unbound('j')))))

In [13]:
C_indexed

Scalar(Content(CallUnary(GetItem(CallUnary(GetItem(Unbound('')),
                                           Content(Unbound('i')))),
                         Content(Unbound('j')))))

In [14]:
assert replace(Index(vector_of(i, j), C_transposed_identity)) == C_indexed

#### Tranpose

In [15]:
C_transposed = Transpose(vector(1, 0), C)
replace(C_transposed)

Sequence(Unbound('', variable_name=B_shape_1),
         UnaryFunction(Sequence(Unbound('', variable_name=B_shape_0),
                                UnaryFunction(Scalar(Content(CallUnary(GetItem(CallUnary(GetItem(Unbound('')),
                                                                                         Unbound(''))),
                                                                       Unbound('')))),
                                              Unbound('', variable_name=i22))),
                       Unbound('', variable_name=i19)))

In [16]:
replace(Index(vector_of(i, j), C_transposed))

Scalar(Content(CallUnary(GetItem(CallUnary(GetItem(Unbound('')),
                                           Content(Unbound('j')))),
                         Content(Unbound('i')))))

## NumPy testing

In [17]:
@optimize
def numpy_transpose(a: LazyNDArray):
    a = a.has_dim(2)
    # identity
    return Transpose(vector(1, 0), a.expr)

In [18]:
print(numpy_transpose.__optimize_steps__["ast_as_source"])



def fn(a):
    i_7 = ()
    i_8 = a.shape[0]
    i_5 = ((i_8,) + i_7)
    i_6 = a.shape[1]
    i_1 = ((i_6,) + i_5)
    i_0 = np.empty(i_1)
    i_2 = a.shape[1]
    for i_3 in range(i_2):
        i_4 = i_0[i_3]
        i_9 = a.shape[0]
        for i_10 in range(i_9):
            i_11 = i_4[i_10]
            i_12 = i_3
            i_14 = i_10
            i_15 = a
            i_13 = i_15[i_14]
            i_11 = i_13[i_12]
            i_4[i_10] = i_11
        i_0[i_3] = i_4
    return i_0



In [19]:
A = np.arange(12, dtype="float64").reshape(4, 3)
A

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [23]:
np.transpose(A, (1, 0))

array([[ 0.,  3.,  6.,  9.],
       [ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.]])

In [24]:
numpy_transpose(A)

array([[ 0.,  3.,  6.,  9.],
       [ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.]])