In [1]:
from uarray import *
import matchpy

In [2]:
class Reverse(matchpy.Operation):
    """
    Reverse(array)
    """
    name = "Reverse"
    arity = matchpy.Arity(1, False)

In [3]:
def _reverse_sequence(length, getitem):
    def new_getitem(idx):
        return Call(getitem, Add(Multiply(idx, Value(-1)), Add(length, Value(-1))))
    
    return Sequence(
        length,
        function(1, new_getitem)
    )

register(Reverse(Sequence(w.length, w.getitem)), _reverse_sequence)

In [19]:
@optimize
def try_reversing(a):
    a = a.has_dim(2)
    return OmegaUnary(function(1, Reverse), Value(1), a.expr)

In [17]:
print(try_reversing.__optimize_steps__["ast_as_source"])



def fn(a):
    i_46 = ()
    i_47 = a.shape[1]
    i_44 = ((i_47,) + i_46)
    i_45 = a.shape[0]
    i_40 = ((i_45,) + i_44)
    i_39 = np.empty(i_40)
    i_41 = a.shape[0]
    for i_42 in range(i_41):
        i_43 = i_39[i_42]
        i_48 = a.shape[1]
        for i_49 in range(i_48):
            i_50 = i_43[i_49]
            i_51 = i_49
            i_57 = i_42
            i_58 = -1
            i_55 = (i_57 * i_58)
            i_59 = a.shape[0]
            i_60 = -1
            i_56 = (i_59 + i_60)
            i_53 = (i_55 + i_56)
            i_54 = a
            i_52 = i_54[i_53]
            i_50 = i_52[i_51]
            i_43[i_49] = i_50
        i_39[i_42] = i_43
    return i_39



In [13]:
np.arange(10, dtype="float64").reshape(2, 5)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [12]:
try_reversing(np.arange(10, dtype="float64").reshape(2, 5))

array([[5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4.]])

In [20]:
try_reversing(np.arange(10, dtype="float64").reshape(2, 5))

array([[4., 3., 2., 1., 0.],
       [9., 8., 7., 6., 5.]])