In [59]:
from uarray import *
from numba import njit

In [60]:
def some_function(a, b):
    return (a + b)[10]

In [61]:
a = np.arange(1000 * 1000, dtype="float64").reshape(1000, 1000)
b = np.arange(1000, dtype="float64")

In [62]:
some_function(a, b)

array([10000., 10002., 10004., 10006., 10008., 10010., 10012., 10014.,
       10016., 10018., 10020., 10022., 10024., 10026., 10028., 10030.,
       10032., 10034., 10036., 10038., 10040., 10042., 10044., 10046.,
       10048., 10050., 10052., 10054., 10056., 10058., 10060., 10062.,
       10064., 10066., 10068., 10070., 10072., 10074., 10076., 10078.,
       10080., 10082., 10084., 10086., 10088., 10090., 10092., 10094.,
       10096., 10098., 10100., 10102., 10104., 10106., 10108., 10110.,
       10112., 10114., 10116., 10118., 10120., 10122., 10124., 10126.,
       10128., 10130., 10132., 10134., 10136., 10138., 10140., 10142.,
       10144., 10146., 10148., 10150., 10152., 10154., 10156., 10158.,
       10160., 10162., 10164., 10166., 10168., 10170., 10172., 10174.,
       10176., 10178., 10180., 10182., 10184., 10186., 10188., 10190.,
       10192., 10194., 10196., 10198., 10200., 10202., 10204., 10206.,
       10208., 10210., 10212., 10214., 10216., 10218., 10220., 10222.,
      

In [63]:
some_function(a, b)
%timeit some_function(a, b)

1.11 ms ± 35.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [64]:
some_fun_njit = njit(some_function)
some_fun_njit(a, b)

array([10000., 10002., 10004., 10006., 10008., 10010., 10012., 10014.,
       10016., 10018., 10020., 10022., 10024., 10026., 10028., 10030.,
       10032., 10034., 10036., 10038., 10040., 10042., 10044., 10046.,
       10048., 10050., 10052., 10054., 10056., 10058., 10060., 10062.,
       10064., 10066., 10068., 10070., 10072., 10074., 10076., 10078.,
       10080., 10082., 10084., 10086., 10088., 10090., 10092., 10094.,
       10096., 10098., 10100., 10102., 10104., 10106., 10108., 10110.,
       10112., 10114., 10116., 10118., 10120., 10122., 10124., 10126.,
       10128., 10130., 10132., 10134., 10136., 10138., 10140., 10142.,
       10144., 10146., 10148., 10150., 10152., 10154., 10156., 10158.,
       10160., 10162., 10164., 10166., 10168., 10170., 10172., 10174.,
       10176., 10178., 10180., 10182., 10184., 10186., 10188., 10190.,
       10192., 10194., 10196., 10198., 10200., 10202., 10204., 10206.,
       10208., 10210., 10212., 10214., 10216., 10218., 10220., 10222.,
      

In [65]:
%timeit some_fun_njit(a, b)

834 µs ± 66.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [66]:
opt = optimize(a.shape, b.shape)(some_function)

In [67]:
opt(a, b)

array([10000., 10002., 10004., 10006., 10008., 10010., 10012., 10014.,
       10016., 10018., 10020., 10022., 10024., 10026., 10028., 10030.,
       10032., 10034., 10036., 10038., 10040., 10042., 10044., 10046.,
       10048., 10050., 10052., 10054., 10056., 10058., 10060., 10062.,
       10064., 10066., 10068., 10070., 10072., 10074., 10076., 10078.,
       10080., 10082., 10084., 10086., 10088., 10090., 10092., 10094.,
       10096., 10098., 10100., 10102., 10104., 10106., 10108., 10110.,
       10112., 10114., 10116., 10118., 10120., 10122., 10124., 10126.,
       10128., 10130., 10132., 10134., 10136., 10138., 10140., 10142.,
       10144., 10146., 10148., 10150., 10152., 10154., 10156., 10158.,
       10160., 10162., 10164., 10166., 10168., 10170., 10172., 10174.,
       10176., 10178., 10180., 10182., 10184., 10186., 10188., 10190.,
       10192., 10194., 10196., 10198., 10200., 10202., 10204., 10206.,
       10208., 10210., 10212., 10214., 10216., 10218., 10220., 10222.,
      

In [68]:
print(opt.__optimize_steps__['ast_as_source'])



def fn(a, b):
    i_227 = ()
    i_228 = 1000
    i_223 = ((i_228,) + i_227)
    i_216 = np.empty(i_223)
    i_224 = 1000
    for i_225 in range(i_224):
        i_226 = i_216[i_225]
        i_219 = i_225
        i_217 = 10
        i_218 = a
        i_220 = i_218[i_217]
        i_229 = i_220[i_219]
        i_221 = i_225
        i_222 = b
        i_230 = i_222[i_221]
        i_226 = (i_229 + i_230)
        i_216[i_225] = i_226
    return i_216



In [69]:
opt(a, b)
%timeit opt(a, b)

592 µs ± 6.46 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [70]:
n_opt = njit(opt)
n_opt(a, b)

array([10000., 10002., 10004., 10006., 10008., 10010., 10012., 10014.,
       10016., 10018., 10020., 10022., 10024., 10026., 10028., 10030.,
       10032., 10034., 10036., 10038., 10040., 10042., 10044., 10046.,
       10048., 10050., 10052., 10054., 10056., 10058., 10060., 10062.,
       10064., 10066., 10068., 10070., 10072., 10074., 10076., 10078.,
       10080., 10082., 10084., 10086., 10088., 10090., 10092., 10094.,
       10096., 10098., 10100., 10102., 10104., 10106., 10108., 10110.,
       10112., 10114., 10116., 10118., 10120., 10122., 10124., 10126.,
       10128., 10130., 10132., 10134., 10136., 10138., 10140., 10142.,
       10144., 10146., 10148., 10150., 10152., 10154., 10156., 10158.,
       10160., 10162., 10164., 10166., 10168., 10170., 10172., 10174.,
       10176., 10178., 10180., 10182., 10184., 10186., 10188., 10190.,
       10192., 10194., 10196., 10198., 10200., 10202., 10204., 10206.,
       10208., 10210., 10212., 10214., 10216., 10218., 10220., 10222.,
      

In [71]:
%timeit n_opt(a, b)

1.19 µs ± 25.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
